% analyze the result of BUG_sweep20210508.m

clear
solution_name='for_paper210415';
% pwd == the root of DSA
addpath(genpath(['./others/' solution_name '/']))
addpath(genpath('./packages'))

d1=@(mat,ip) reshape(mat(ip,1,:),1,3);
d2=@(mat,iPin) reshape(mat(:,1,iPin),1,3);
o=@(mat) mat([1,4,7,2,5,8,3,6,9]');

%% sweep
% results
% experiment and fem model
% get_BUG_resultsmat();
load('BUG_results.mat')
% transformer_base
load('paper_BUG_edge_t210517.mat')
plasma_t=input.plasma;
source_t=source;
% analytical_base
load('paper_BUG_edge_a210517.mat')
plasma_a=input.plasma;
source_a=source;
% transformer_2018Jainb
load('paper_BUG_edge_tj210517.mat')
plasma_tj=input.plasma;
source_tj=source;

h_fig=plot_nY(d2(plasma_t.p,1),'p [Pa]',...
    d2(plasma_t.nu_m,1),'\nu_m, Pin=18kW',...
    d2(plasma_t.nu_m,2),'\nu_m, Pin=36kW',...
    d2(plasma_t.nu_m,3),'\nu_m, Pin=55kW',...
    d2(plasma_t.nu_st,1),'\nu_{st}, Pin=18kW',...
    d2(plasma_t.nu_st,2),'\nu_{st}, Pin=36kW',...
    d2(plasma_t.nu_st,3),'\nu_{st}, Pin=55kW',...
    d2(plasma_t.nu_eff,1),'\nu_{eff}, Pin=18kW',...
    d2(plasma_t.nu_eff,2),'\nu_{eff}, Pin=36kW',...
    d2(plasma_t.nu_eff,3),'\nu_{eff}, Pin=55kW',...
    'frequency [s^{-1}]','semilogy');

h_fig=plot_nY(d2(plasma_t.p,1),'p [Pa]',...
    d2(plasma_t.nu_st,1)./d2(plasma_t.nu_m,1),'\nu_{st}/\nu_m, Pin=18kW',...
    d2(plasma_t.nu_st,2)./d2(plasma_t.nu_m,2),'\nu_{st}/\nu_m, Pin=36kW',...
    d2(plasma_t.nu_st,3)./d2(plasma_t.nu_m,3),'\nu_{st}/\nu_m, Pin=55kW',...
    'frequency [s^{-1}]','semilogy');

h_fig=plot_nY(d2(plasma_t.p,1),'p [Pa]',...
    d2(experiment.PER,1),'subtractive, Pin=18kW',...
    d2(experiment.PER,2),'subtractive, Pin=36kW',...
    d2(experiment.PER,3),'subtractive, Pin=55kW',...
    d2(source_t.PER,1),'t, Pin=18kW',...
    d2(source_t.PER,2),'t, Pin=36kW',...
    d2(source_t.PER,3),'t, Pin=55kW',...
    d2(source_a.PER,1),'a, Pin=18kW',...
    d2(source_a.PER,2),'a, Pin=36kW',...
    d2(source_a.PER,3),'a, Pin=55kW',...
    d2(fem.PER,1),'fem, Pin=18kW',...
    d2(fem.PER,2),'fem, Pin=36kW',...
    d2(fem.PER,3),'fem, Pin=55kW',...
    'PER [\Omega]','semilogy');


h_fig=plot_nY(d1(plasma_t.Pin,1),'{\itP}_{in} [kW]',...
    d1(experiment.PER,1),'subtractive-0.2Pa',...
    d1(experiment.PER,2),'subtractive-0.3Pa',...
    d1(experiment.PER,3),'subtractive-0.5Pa',...
    d1(source_t.PER,1),'transformer-0.2Pa',...
    d1(source_t.PER,2),'transformer-0.3Pa',...
    d1(source_t.PER,3),'transformer-0.5Pa',...
    d1(source_tj.PER,1),'transformerJ-0.2Pa',...
    d1(source_tj.PER,2),'transformerJ-0.3Pa',...
    d1(source_tj.PER,3),'transformerJ-0.5Pa',...
    d1(source_a.PER,1),'analytical EM-0.2Pa',...
    d1(source_a.PER,2),'analytical EM-0.3Pa',...
    d1(source_a.PER,3),'analytical EM-0.5Pa',...
    'PER [\Omega]','plot');

h_fig=plot_nY(d1(plasma_t.Pin,1),'{\itP}_{in} [kW]',...
    d1(experiment.PER,1),'subtractive-0.2Pa',...
    d1(source_t.PER,1),'transformer-0.2Pa',...
    d1(source_a.PER,1),'analytical EM-0.2Pa',...
    'PER [\Omega]','plot');

h_fig=plot_nY(d1(plasma_t.Pin,1),'{\itP}_{in} [kW]',...
    d1(experiment.PER,1),'subtractive-0.2Pa',...
    d1(experiment.PER,2),'subtractive-0.3Pa',...
    d1(experiment.PER,3),'subtractive-0.5Pa',...
    d1(source_t.PER,1),'transformer-0.2Pa',...
    d1(source_t.PER,2),'transformer-0.3Pa',...
    d1(source_t.PER,3),'transformer-0.5Pa',...
    'PER [\Omega]','semilogy');

% 无法使用同一Pplasma比较PER，因为同一Icoil不同PER计算出来的Pplasma会差别很大
handle_fig=figure;
legend_text={};
plot(d1(experiment.Pplasma,1),d1(experiment.PER,1),'-r')
hold on
plot(d1(source_t.Pplasma,1),d1(source_t.PER,1),'-b')



constants=get_constants();
%% 磁化
r1=0;
r2=input.geometry.r_plasma_eff;

load('BUG_edge_sweep210508.mat')
p0=input.plasma;
source=analytical_EM_model( flag, input );

flag.output_plasma_model=true;
[input1, source1]=get_magnetized(flag,input,source);


% 迭代
[input1, source1]=get_magnetized(flag,input1,source1);
[input1, source1]=get_magnetized(flag,input1,source1);
[input1, source1]=get_magnetized(flag,input1,source1);

% output
p1=input1.plasma;
p=[0.2,0.3,0.5];
h_fig=plot_nY(p,'{\itp} [Pa]',...
    d2(p1.w_ce,1),'wce, 18kW',...
    d2(p1.w_ce,2),'wce, 36kW',...
    d2(p1.w_ce,3),'wce, 55kW',...
    d2(p1.nu_eff,1),'\nu_{eff}, 18kW',...
    d2(p1.nu_eff,2),'\nu_{eff}, 36kW',...
    d2(p1.nu_eff,3),'\nu_{eff}, 55kW',...
    '\omega [s^{-1}]','loglog');

h_fig=plot_nY(d2(plasma_t.p,1),'p [Pa]',...
    d2(experiment.PER,1),'subtractive, Pin=18kW',...
    d2(experiment.PER,2),'subtractive, Pin=36kW',...
    d2(experiment.PER,3),'subtractive, Pin=55kW',...
    d2(source_t.PER,1),'t, Pin=18kW',...
    d2(source_t.PER,2),'t, Pin=36kW',...
    d2(source_t.PER,3),'t, Pin=55kW',...
    d2(source_a.PER,1),'a, Pin=18kW',...
    d2(source_a.PER,2),'a, Pin=36kW',...
    d2(source_a.PER,3),'a, Pin=55kW',...
    d2(source.PER,1),'m, Pin=18kW',...
    d2(source.PER,2),'m, Pin=36kW',...
    d2(source.PER,3),'m, Pin=55kW',...
    'PER [\Omega]','plot');



% 20210514  TODO





o(p1.eps_r)
o(p1.sigma)


we=-p1.w_RF.*p1.eps_prime;
h_fig=plot_nY(p,'{\itp} [Pa]',...
    p1.sigma(:,1),'\sigma, 1MHz',...
    we(:,1),'-\omega\epsilon, 1MHz',...
    p1.sigma(:,2),'\sigma, 4MHz',...
    we(:,2),'-\omega\epsilon, 4MHz',...
    '','loglog');





r=r1:(r2-r1)/100:r2;
Bm=@(H,r) constants.mu0*abs(H(r));

    len_r=length(r);
    B0=zeros(1,len_r);
    B1=B0;
    for i_r=1:len_r
        temp=Bm(source.emf.Hz_plasma,r(i_r));
        B0(i_r)=temp(end,1);
    end
    
    h_fig=plot_nY(r,'r [m]',...
        B0,'before, 1MHz, 10Pa',...
        'Bm [T]','plot');
    xticks('auto')


% 2021Zielke称趋肤层有数mT的磁场
B0=3e-3;
w_ce=constants.e*B0/constants.me;
find(plasma_t.nu_eff>w_ce)
factor=sqrt(1+w_ce.^2./plasma_t.ve.^2);

sigma1=plasma_t.sigma_dc.*factor;
eps1=constants.eps0;
% 根据猜测做调整
sigma_c=plasma_t.sigma_c.*factor;
sigma2=real(sigma_c);
eps2=imag(sigma_c)./plasma_t.w_RF;

get_eps_c=@(sigma, eps, omega) eps-1i*sigma./omega;
p1=plasma_t;
p1.eps_c=get_eps_c(sigma1,eps1,p1.w_RF);
p1 = wave_analysis( p1, '' );
input1=input;
input1.plasma=p1;
s1=analytical_EM_model( flag, input1 );

p2=plasma_t;
p2.eps_c=get_eps_c(sigma2,eps2,p2.w_RF);
p2 = wave_analysis( p2, '' );
input2=input;
input2.plasma=p2;
s2=analytical_EM_model( flag, input2 );

h_fig=plot_nY(d2(plasma_t.p,1),'p [Pa]',...
    d2(experiment.PER,1),'subtractive, Pin=18kW',...
    d2(experiment.PER,2),'subtractive, Pin=36kW',...
    d2(experiment.PER,3),'subtractive, Pin=55kW',...
    d2(source_t.PER,1),'t, Pin=18kW',...
    d2(source_t.PER,2),'t, Pin=36kW',...
    d2(source_t.PER,3),'t, Pin=55kW',...
    d2(source_a.PER,1),'a, Pin=18kW',...
    d2(source_a.PER,2),'a, Pin=36kW',...
    d2(source_a.PER,3),'a, Pin=55kW',...
    d2(s1.PER,1),'1998Tuszewski-1, Pin=18kW',...
    d2(s1.PER,2),'1998Tuszewski-1, Pin=36kW',...
    d2(s1.PER,3),'1998Tuszewski-1, Pin=55kW',...
    d2(s2.PER,1),'1998Tuszewski-2, Pin=18kW',...
    d2(s2.PER,2),'1998Tuszewski-2, Pin=36kW',...
    d2(s2.PER,3),'1998Tuszewski-2, Pin=55kW',...
    'frequency [s^{-1}]','semilogy');

% 磁化-循环
o_source=s1;
o_Hz_center=o_source.emf.Hz_plasma(1);
o_Bz_center=constants.mu0*abs(o_Hz_center)
o_source=s2;
o_Hz_center=o_source.emf.Hz_plasma(1);
o_Bz_center=constants.mu0*abs(o_Hz_center)

